"""add devise to ecole

Revision ID: 056e1721ee87
Revises: a9a89fc76b32
Create Date: 2026-09-30 17:07:39.260612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056e1721ee87'
down_revision = 'a9a89fc76b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecole', schema=None) as batch_op:
        batch_op.drop_column('devise')

    # ### end Alembic commands ###
