"""add_facturer_juillet_annee_scolaire

Revision ID: 333fb6b8679b
Revises: 06d6ed759c6e
Create Date: 2026-09-19 03:19:41.881586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333fb6b8679b'
down_revision = '06d6ed759c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annee_scolaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facturer_juillet', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annee_scolaire', schema=None) as batch_op:
        batch_op.drop_column('facturer_juillet')

    # ### end Alembic commands ###
