"""add performance composite indexes

Revision ID: 344198f5585e
Revises: f0223a6b1ae2
Create Date: 2026-09-09 21:23:13.272555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344198f5585e'
down_revision = 'f0223a6b1ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('ix_absence_ecole_eleve', ['ecole_id', 'eleve_id'], unique=False)

    with op.batch_alter_table('classe', schema=None) as batch_op:
        batch_op.create_index('ix_classe_ecole_annee', ['ecole_id', 'annee_scolaire_id'], unique=False)

    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.create_index('ix_cours_ecole_classe', ['ecole_id', 'classe_id'], unique=False)

    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.create_index('ix_eleve_ecole_classe', ['ecole_id', 'classe_id'], unique=False)
        batch_op.create_index('ix_eleve_parent_id', ['parent_id'], unique=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('ix_note_cours_eleve', ['cours_id', 'eleve_id'], unique=False)
        batch_op.create_index('ix_note_ecole_eleve', ['ecole_id', 'eleve_id'], unique=False)

    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.create_index('ix_paiement_ecole_statut', ['ecole_id', 'statut'], unique=False)

    with op.batch_alter_table('professeur', schema=None) as batch_op:
        batch_op.create_index('ix_professeur_utilisateur_ecole', ['utilisateur_id', 'ecole_id'], unique=False)

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.create_index('ix_utilisateur_ecole_role', ['ecole_id', 'role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_index('ix_utilisateur_ecole_role')

    with op.batch_alter_table('professeur', schema=None) as batch_op:
        batch_op.drop_index('ix_professeur_utilisateur_ecole')

    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.drop_index('ix_paiement_ecole_statut')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index('ix_note_ecole_eleve')
        batch_op.drop_index('ix_note_cours_eleve')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.drop_index('ix_eleve_parent_id')
        batch_op.drop_index('ix_eleve_ecole_classe')

    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.drop_index('ix_cours_ecole_classe')

    with op.batch_alter_table('classe', schema=None) as batch_op:
        batch_op.drop_index('ix_classe_ecole_annee')

    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.drop_index('ix_absence_ecole_eleve')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
