"""add_ecole_google_mail_config

Revision ID: 4e3f1048a0e2
Revises: a8c7e2b1d5f3
Create Date: 2026-09-07 23:21:53.417033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3f1048a0e2'
down_revision = 'a8c7e2b1d5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecole_google_mail_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('google_email', sa.String(length=120), nullable=True),
    sa.Column('google_refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('google_access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ecole_id'], ['ecole.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecole_google_mail_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecole_google_mail_config_ecole_id'), ['ecole_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecole_google_mail_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecole_google_mail_config_ecole_id'))

    op.drop_table('ecole_google_mail_config')
    # ### end Alembic commands ###
