"""add_performance_indexes

Revision ID: a9a89fc76b32
Revises: e6f7a8b9c0d1
Create Date: 2026-09-29 21:53:05.165755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a89fc76b32'
down_revision = 'e6f7a8b9c0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emploi_temps', schema=None) as batch_op:
        batch_op.create_index('ix_emploi_temps_ecole', ['ecole_id'], unique=False)

    with op.batch_alter_table('journal_corrections', schema=None) as batch_op:
        batch_op.create_index('ix_journal_correction_action', ['action'], unique=False)
        batch_op.create_index('ix_journal_correction_cible', ['cible_type', 'cible_id'], unique=False)
        batch_op.create_index('ix_journal_correction_ecole_cible_date', ['ecole_id', 'cible_type', 'date'], unique=False)

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_index('ix_log_ecole_timestamp', ['ecole_id', 'timestamp'], unique=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index('ix_note_inscription_cours', ['inscription_id', 'cours_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index('ix_note_inscription_cours')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_index('ix_log_ecole_timestamp')

    with op.batch_alter_table('journal_corrections', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_correction_ecole_cible_date')
        batch_op.drop_index('ix_journal_correction_cible')
        batch_op.drop_index('ix_journal_correction_action')

    with op.batch_alter_table('emploi_temps', schema=None) as batch_op:
        batch_op.drop_index('ix_emploi_temps_ecole')

    # ### end Alembic commands ###
