"""add_support_ticket

Revision ID: f0223a6b1ae2
Revises: 6a7b8c9d0e1f
Create Date: 2026-09-09 18:09:08.857780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0223a6b1ae2'
down_revision = '6a7b8c9d0e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('sujet', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ecole_id'], ['ecole.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_ticket_ecole_id'), ['ecole_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_utilisateur_id'), ['utilisateur_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_ticket_utilisateur_id'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_statut'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_ecole_id'))

    op.drop_table('support_ticket')
    # ### end Alembic commands ###
